# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 369c98bceeaa40052aaa56880e1937f05d9952a39275d1f94452be3f2771c3418c7321662b556e2e163f663c3500d241dd3f784b8046445ea1ebac91a15f2ae8

test:
  secret_key_base: 3b88c564f9edb24c1e4fd7f45d6313a10a6e8b434cdb88ec2e6f910ffe487f69bf77d62770154d5ab3d8d6b74b9bc4e5e7ac2f9d2010781c99076304d2a32e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
